In [1]:
import pandas as pd

In [4]:
df = pd.read_csv(r"C:\Users\sridhar rathod\Downloads\global_ecommerce_forecasting.csv")

In [5]:
df

,order_datetime,year,month,week_of_year,day_of_week,order_hour,is_weekend,country,country_code,product_id,customer_id,unit_price_gbp,quantity_sold,sales_amount_gbp,population_total,gdp_current_usd,gdp_growth_pct,inflation_consumer_pct
0,2009-12-01 07:45:00,2009,12,49,1,7,0,United Kingdom,GBR,21523,13085,5.95,10,59.50,62276270.0,2.412840e+12,-17.633976,1.897090
1,2009-12-01 07:45:00,2009,12,49,1,7,0,United Kingdom,GBR,79323W,13085,6.75,12,81.00,62276270.0,2.412840e+12,-17.633976,1.897090
2,2009-12-01 09:06:00,2009,12,49,1,9,0,United Kingdom,GBR,82582,13078,2.10,12,25.20,62276270.0,2.412840e+12,-17.633976,1.897090
3,2009-12-01 09:06:00,2009,12,49,1,9,0,United Kingdom,GBR,22111,13078,4.25,24,102.00,62276270.0,2.412840e+12,-17.633976,1.897090
4,2009-12-01 09:06:00,2009,12,49,1,9,0,United Kingdom,GBR,21756,13078,5.95,3,17.85,62276270.0,2.412840e+12,-17.633976,1.897090
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,2010-12-09 20:01:00,2010,12,49,3,20,0,United Kingdom,GBR,22751,17530,3.75,1,3.75,62766365.0,2.485483e+12,3.010668,1.589081
99996,2010-12-09 20:01:00,2010,12,49,3,20,0,United Kingdom,GBR,21931,17530,1.95,2,3.90,62766365.0,2.485483e+12,3.010668,1.589081
99997,2010-12-09 20:01:00,2010,12,49,3,20,0,United Kingdom,GBR,21034,17530,0.95,1,0.95,62766365.0,2.485483e+12,3.010668,1.589081
99998,2010-12-09 20:01:00,2010,12,49,3,20,0,United Kingdom,GBR,22367,17530,1.95,4,7.80,62766365.0,2.485483e+12,3.010668,1.589081
99999,2010-12-09 20:01:00,2010,12,49,3,20,0,United Kingdom,GBR,21592,17530,1.25,4,5.00,62766365.0,2.485483e+12,3.010668,1.589081

In [6]:
df.head(10000-9000)

,order_datetime,year,month,week_of_year,day_of_week,order_hour,is_weekend,country,country_code,product_id,customer_id,unit_price_gbp,quantity_sold,sales_amount_gbp,population_total,gdp_current_usd,gdp_growth_pct,inflation_consumer_pct
0,2009-12-01 07:45:00,2009,12,49,1,7,0,United Kingdom,GBR,21523,13085,5.95,10,59.50,62276270.0,2.412840e+12,-17.633976,1.89709
1,2009-12-01 07:45:00,2009,12,49,1,7,0,United Kingdom,GBR,79323W,13085,6.75,12,81.00,62276270.0,2.412840e+12,-17.633976,1.89709
2,2009-12-01 09:06:00,2009,12,49,1,9,0,United Kingdom,GBR,82582,13078,2.10,12,25.20,62276270.0,2.412840e+12,-17.633976,1.89709
3,2009-12-01 09:06:00,2009,12,49,1,9,0,United Kingdom,GBR,22111,13078,4.25,24,102.00,62276270.0,2.412840e+12,-17.633976,1.89709
4,2009-12-01 09:06:00,2009,12,49,1,9,0,United Kingdom,GBR,21756,13078,5.95,3,17.85,62276270.0,2.412840e+12,-17.633976,1.89709
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,2009-12-02 16:02:00,2009,12,49,2,16,0,United Kingdom,GBR,17084G,17660,0.21,25,5.25,62276270.0,2.412840e+12,-17.633976,1.89709
996,2009-12-02 16:02:00,2009,12,49,2,16,0,United Kingdom,GBR,22294,17660,1.25,2,2.50,62276270.0,2.412840e+12,-17.633976,1.89709
997,2009-12-02 16:02:00,2009,12,49,2,16,0,United Kingdom,GBR,21615,17660,3.75,1,3.75,62276270.0,2.412840e+12,-17.633976,1.89709
998,2009-12-02 16:02:00,2009,12,49,2,16,0,United Kingdom,GBR,20865,17660,2.10,1,2.10,62276270.0,2.412840e+12,-17.633976,1.89709
999,2009-12-02 16:02:00,2009,12,49,2,16,0,United Kingdom,GBR,20974,17660,0.65,1,0.65,62276270.0,2.412840e+12,-17.633976,1.89709

In [7]:
df.drop_duplicates()

,order_datetime,year,month,week_of_year,day_of_week,order_hour,is_weekend,country,country_code,product_id,customer_id,unit_price_gbp,quantity_sold,sales_amount_gbp,population_total,gdp_current_usd,gdp_growth_pct,inflation_consumer_pct
0,2009-12-01 07:45:00,2009,12,49,1,7,0,United Kingdom,GBR,21523,13085,5.95,10,59.50,62276270.0,2.412840e+12,-17.633976,1.897090
1,2009-12-01 07:45:00,2009,12,49,1,7,0,United Kingdom,GBR,79323W,13085,6.75,12,81.00,62276270.0,2.412840e+12,-17.633976,1.897090
2,2009-12-01 09:06:00,2009,12,49,1,9,0,United Kingdom,GBR,82582,13078,2.10,12,25.20,62276270.0,2.412840e+12,-17.633976,1.897090
3,2009-12-01 09:06:00,2009,12,49,1,9,0,United Kingdom,GBR,22111,13078,4.25,24,102.00,62276270.0,2.412840e+12,-17.633976,1.897090
4,2009-12-01 09:06:00,2009,12,49,1,9,0,United Kingdom,GBR,21756,13078,5.95,3,17.85,62276270.0,2.412840e+12,-17.633976,1.897090
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,2010-12-09 20:01:00,2010,12,49,3,20,0,United Kingdom,GBR,22751,17530,3.75,1,3.75,62766365.0,2.485483e+12,3.010668,1.589081
99996,2010-12-09 20:01:00,2010,12,49,3,20,0,United Kingdom,GBR,21931,17530,1.95,2,3.90,62766365.0,2.485483e+12,3.010668,1.589081
99997,2010-12-09 20:01:00,2010,12,49,3,20,0,United Kingdom,GBR,21034,17530,0.95,1,0.95,62766365.0,2.485483e+12,3.010668,1.589081
99998,2010-12-09 20:01:00,2010,12,49,3,20,0,United Kingdom,GBR,22367,17530,1.95,4,7.80,62766365.0,2.485483e+12,3.010668,1.589081
99999,2010-12-09 20:01:00,2010,12,49,3,20,0,United Kingdom,GBR,21592,17530,1.25,4,5.00,62766365.0,2.485483e+12,3.010668,1.589081

In [9]:
df['order_datetime'] = pd.to_datetime(df['order_datetime'], errors = 'coerce' )

In [10]:
df =df.dropna(subset=['order_datetime'])

In [11]:
df

,order_datetime,year,month,week_of_year,day_of_week,order_hour,is_weekend,country,country_code,product_id,customer_id,unit_price_gbp,quantity_sold,sales_amount_gbp,population_total,gdp_current_usd,gdp_growth_pct,inflation_consumer_pct
0,2009-12-01 07:45:00,2009,12,49,1,7,0,United Kingdom,GBR,21523,13085,5.95,10,59.50,62276270.0,2.412840e+12,-17.633976,1.897090
1,2009-12-01 07:45:00,2009,12,49,1,7,0,United Kingdom,GBR,79323W,13085,6.75,12,81.00,62276270.0,2.412840e+12,-17.633976,1.897090
2,2009-12-01 09:06:00,2009,12,49,1,9,0,United Kingdom,GBR,82582,13078,2.10,12,25.20,62276270.0,2.412840e+12,-17.633976,1.897090
3,2009-12-01 09:06:00,2009,12,49,1,9,0,United Kingdom,GBR,22111,13078,4.25,24,102.00,62276270.0,2.412840e+12,-17.633976,1.897090
4,2009-12-01 09:06:00,2009,12,49,1,9,0,United Kingdom,GBR,21756,13078,5.95,3,17.85,62276270.0,2.412840e+12,-17.633976,1.897090
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,2010-12-09 20:01:00,2010,12,49,3,20,0,United Kingdom,GBR,22751,17530,3.75,1,3.75,62766365.0,2.485483e+12,3.010668,1.589081
99996,2010-12-09 20:01:00,2010,12,49,3,20,0,United Kingdom,GBR,21931,17530,1.95,2,3.90,62766365.0,2.485483e+12,3.010668,1.589081
99997,2010-12-09 20:01:00,2010,12,49,3,20,0,United Kingdom,GBR,21034,17530,0.95,1,0.95,62766365.0,2.485483e+12,3.010668,1.589081
99998,2010-12-09 20:01:00,2010,12,49,3,20,0,United Kingdom,GBR,22367,17530,1.95,4,7.80,62766365.0,2.485483e+12,3.010668,1.589081
99999,2010-12-09 20:01:00,2010,12,49,3,20,0,United Kingdom,GBR,21592,17530,1.25,4,5.00,62766365.0,2.485483e+12,3.010668,1.589081

In [18]:
df

,order_datetime,year,month,week_of_year,day_of_week,order_hour,is_weekend,country,country_code,product_id,customer_id,unit_price_gbp,quantity_sold,sales_amount_gbp,population_total,gdp_current_usd,gdp_growth_pct,inflation_consumer_pct
0,2009-12-01 07:45:00,2009,12,49,1,7,0,United Kingdom,GBR,21523,13085,5.95,10,59.50,62276270.0,2.412840e+12,-17.633976,1.897090
1,2009-12-01 07:45:00,2009,12,49,1,7,0,United Kingdom,GBR,79323W,13085,6.75,12,81.00,62276270.0,2.412840e+12,-17.633976,1.897090
2,2009-12-01 09:06:00,2009,12,49,1,9,0,United Kingdom,GBR,82582,13078,2.10,12,25.20,62276270.0,2.412840e+12,-17.633976,1.897090
3,2009-12-01 09:06:00,2009,12,49,1,9,0,United Kingdom,GBR,22111,13078,4.25,24,102.00,62276270.0,2.412840e+12,-17.633976,1.897090
4,2009-12-01 09:06:00,2009,12,49,1,9,0,United Kingdom,GBR,21756,13078,5.95,3,17.85,62276270.0,2.412840e+12,-17.633976,1.897090
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,2010-12-09 20:01:00,2010,12,49,3,20,0,United Kingdom,GBR,22751,17530,3.75,1,3.75,62766365.0,2.485483e+12,3.010668,1.589081
99996,2010-12-09 20:01:00,2010,12,49,3,20,0,United Kingdom,GBR,21931,17530,1.95,2,3.90,62766365.0,2.485483e+12,3.010668,1.589081
99997,2010-12-09 20:01:00,2010,12,49,3,20,0,United Kingdom,GBR,21034,17530,0.95,1,0.95,62766365.0,2.485483e+12,3.010668,1.589081
99998,2010-12-09 20:01:00,2010,12,49,3,20,0,United Kingdom,GBR,22367,17530,1.95,4,7.80,62766365.0,2.485483e+12,3.010668,1.589081
99999,2010-12-09 20:01:00,2010,12,49,3,20,0,United Kingdom,GBR,21592,17530,1.25,4,5.00,62766365.0,2.485483e+12,3.010668,1.589081

In [21]:
df['week_of_year']-df['week_of_year']

0        0
1        0
2        0
3        0
4        0
        ..
99995    0
99996    0
99997    0
99998    0
99999    0
Name: week_of_year, Length: 100000, dtype: int64

In [22]:
df

,order_datetime,year,month,week_of_year,day_of_week,order_hour,is_weekend,country,country_code,product_id,customer_id,unit_price_gbp,quantity_sold,sales_amount_gbp,population_total,gdp_current_usd,gdp_growth_pct,inflation_consumer_pct
0,2009-12-01 07:45:00,2009,12,49,1,7,0,United Kingdom,GBR,21523,13085,5.95,10,59.50,62276270.0,2.412840e+12,-17.633976,1.897090
1,2009-12-01 07:45:00,2009,12,49,1,7,0,United Kingdom,GBR,79323W,13085,6.75,12,81.00,62276270.0,2.412840e+12,-17.633976,1.897090
2,2009-12-01 09:06:00,2009,12,49,1,9,0,United Kingdom,GBR,82582,13078,2.10,12,25.20,62276270.0,2.412840e+12,-17.633976,1.897090
3,2009-12-01 09:06:00,2009,12,49,1,9,0,United Kingdom,GBR,22111,13078,4.25,24,102.00,62276270.0,2.412840e+12,-17.633976,1.897090
4,2009-12-01 09:06:00,2009,12,49,1,9,0,United Kingdom,GBR,21756,13078,5.95,3,17.85,62276270.0,2.412840e+12,-17.633976,1.897090
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,2010-12-09 20:01:00,2010,12,49,3,20,0,United Kingdom,GBR,22751,17530,3.75,1,3.75,62766365.0,2.485483e+12,3.010668,1.589081
99996,2010-12-09 20:01:00,2010,12,49,3,20,0,United Kingdom,GBR,21931,17530,1.95,2,3.90,62766365.0,2.485483e+12,3.010668,1.589081
99997,2010-12-09 20:01:00,2010,12,49,3,20,0,United Kingdom,GBR,21034,17530,0.95,1,0.95,62766365.0,2.485483e+12,3.010668,1.589081
99998,2010-12-09 20:01:00,2010,12,49,3,20,0,United Kingdom,GBR,22367,17530,1.95,4,7.80,62766365.0,2.485483e+12,3.010668,1.589081
99999,2010-12-09 20:01:00,2010,12,49,3,20,0,United Kingdom,GBR,21592,17530,1.25,4,5.00,62766365.0,2.485483e+12,3.010668,1.589081

In [25]:
df.to_csv("global_ecommerce_forecasting")